function lang_strings() {
	_langstr = {
		cz: {
			menu_file: "Soubor",
			menu_new_file: "Nový soubor",
			menu_open_file: "Otevřít soubor",
			menu_import_image: "Importovat obrázek",
			menu_export_image: "Exportovat obrázek",
			menu_export_layer: "Exportovat vrstvu",
			menu_export_gif: "Exportovat jako GIF",
			menu_save: "Uložit",
			menu_save_as: "Uložit jako",
			brush_option_size: "Velikost",
			brush_option_falloff: "Hrubost",
			brush_option_spacing: "Mezery",
			brush_option_weight: "Rychlost",
			line_option_tension: "Napnutí",
			line_option_closed: "Spojit konce",
			fill_option_tolerancy: "Tolerance",
			toolbar_tool_brush: "Štětec",
			toolbar_tool_line: "Čára",
			toolbar_tool_fill: "Výplň",
			toolbar_tool_eraser: "Guma",
			toolbar_tool_pipette: "Pipeta",
			toolbar_tool_area: "Výběr",
			save_caption: "Uložit",
			load_caption: "Otevřít",
			new_file: "bez názvu",
			menu_lang: "Jazyk",
		},
		en: {
			menu_file: "File",
			menu_new_file: "New file",
			menu_open_file: "Open file",
			menu_import_image: "Import image",
			menu_export_image: "Export image",
			menu_export_layer: "Export layer",
			menu_export_gif: "Export as GIF",
			menu_save: "Save",
			menu_save_as: "Save as",
			brush_option_size: "Size",
			brush_option_falloff: "Hardness",
			brush_option_spacing: "Spacing",
			brush_option_weight: "Speed",
			line_option_tension: "Tension",
			line_option_closed: "Connect ends",
			fill_option_tolerancy: "Tolerancy",
			toolbar_tool_brush: "Brush",
			toolbar_tool_line: "Line",
			toolbar_tool_fill: "Fill",
			toolbar_tool_eraser: "Eraser",
			toolbar_tool_pipette: "Pipette",
			toolbar_tool_area: "Area selection",
			save_caption: "Save",
			load_caption: "Open",
			new_file: "untitled",
			menu_lang: "Language",
		},
	};
}
